name: Deploy WordPress Theme to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'wp-content/themes/Engitech-Theme'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # If you had build steps, they would go here

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'UsmanWordpress'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: 'wp-content/themes/Engitech-Theme'