name: Deploy WordPress Theme to Azure Web App

on:
  push:
    branches:
      - main # This is the branch that will trigger the deployment
    paths:
      - 'wp-content/themes/Engitech-Theme' # Replace with your theme's directory path

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Add any build steps for your theme here
    # - name: Build theme
    #   run: |
    #     cd wp-content/themes/your-theme
    #     npm install
    #     npm run build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'YourAppServiceName' # Replace with your Azure App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: 'wp-content/themes/Engitech-Theme' # Replace with your theme's directory path